# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0002_auto_20161019_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cash',
            field=models.FloatField(default=10000),
        ),
    ]
