# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0003_stock_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cash',
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.IntegerField(max_length=50),
        ),
    ]
