# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0005_auto_20161022_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
