# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0006_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(),
        ),
    ]
