# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0007_auto_20161022_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.CharField(max_length=250),
        ),
    ]
